config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :customers, only: [:show, :create, :edit, :update]
    resources :customers do
      member do
        patch 'unsubscribe'
      end
    end
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    resources :orders, only: [:update, :show]
    #patch 'orders' => 'orders#update', as: 'orders'
    resources :customers, only: [:index, :show]
    resources :items
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top', as: 'top'
  end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adress.rb
class Adress < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :customer
 belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  attribute :adress, :string

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  attribute :status, :integer, default: "0"
  enum status: {入金待ち:0, 入金確認:1,  製作中:2, 発送準備中:3, 発送済み:4}
  attribute :shipping_cost, :integer, default: "500"
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    flash[:notice1] = "You have created item successfully."
    redirect_to admin_items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

 def edit
    @item = Item.find(params[:id])
 end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
      admin_items_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
      root_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/index.html.erb
<%= link_to '商品を確認する', admin_items_path, class: "btn btn-secondary" %>
<%= link_to 'ユーザーを確認する', admin_customers_path, class: "btn btn-secondary" %>
<%= flash[:notice1] %>

  <h1 class ="mt-5">登録ユーザー</h1>
    <table class="table table-hover">
        <tr>
         <th style="width: 20%">名前</th>
         <th>フリガナ</th>
         <th>電話番号</th>
         <th style="width: 20%">メールアドレス</th>
         <th style="width: 40%">住所</th>
         <th>登録日</th>
         <th>更新日</th>
         <th>ステータス</th>
        </tr>
        <% @customers.each do |customer| %>
          <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.last_name %> <%= customer.first_name %>
          <% end %>
          </td>
          <td><%= customer.last_name_kana %> <%= customer.first_name_kana %></td>
          <td><%= customer.telephone_number %></td>
          <td><%= customer.email %></td>
          <td><%= customer.postal_code %><br><%= customer.adress %></td>
          <td><%= customer.created_at %></td>
          <td><%= customer.updated_at %></td>
          <% if customer.is_active %>
            <td class="text-success align-middle text-center">登録中</td>
          <% else %>
            <td class="text-secondary align-middle text-center">解約済み</td>
          <% end %>
        <% end %>
    </table>

app/views/admin/customers/show.html.erb
<div class="container mt-3">
  <div class="mx-auto col-lg-12">
    <div class="row">
      <div class="col-10 offset-1">
        <h3 class="page-title">ユーザー詳細</h3>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <table class="table table-borderless">
          <tr>
            <th style="width: 40%">ユーザー名</th>
            <td><%= @customer.first_name %></td>
            <td><%= @customer.last_name %></td>
          </tr>
          <tr>
            <th>カナ</th>
            <td><%= @customer.first_name_kana %></td>
            <td><%= @customer.last_name_kana %></td>
          </tr>
            <th>電話番号</th>
            <td> <%= @customer.telephone_number %></td>
          </tr>
          </tr>
            <th>メールアドレス</th>
            <td> <%= @customer.email %></td>
          </tr>
          </tr>
            <th>郵便番号</th>
            <td> <%= @customer.postal_code %></td>
          </tr>
          </tr>
            <th>住所</th>
            <td> <%= @customer.adress %></td>
          </tr>
          </tr>
            <th>登録日</th>
            <td> <%= @customer.created_at %></td>
          </tr>
          </tr>
            <th>最終編集日</th>
            <td> <%= @customer.updated_at %></td>
          </tr>
          <tr>
            <th>ステータス</th>
            <td>
              <% if @customer.is_active=="t" %>
              <div class="text-success">登録ユーザー</div>
              <% else %>
              <div class="text-secondary">解約済み</div>
              <% end %>
            </td>
          </tr>
        </table>
       </div>
    </div>
    
    <div class="row">
      <div class="d-flex justify-content-start mt-3">
        <%= link_to "戻る", admin_customers_path, class: "btn btn-primary" %>
      </div>
    </div>
    
  </div>

</div>

app/views/admin/homes/top.html.erb
<%= link_to '商品を確認する', admin_items_path, class: "btn btn-secondary" %>
<%= link_to 'ユーザーを確認する', admin_customers_path, class: "btn btn-secondary" %>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with(model: [:admin, @item], method: :patch) do |f| %>
  <p>タイトル</p>
  <%= f.text_field :name %>

  <p>詳細</p>
  <%= f.text_field :introduction %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <p>価格</p>
  <%= f.text_field :price, placeholder: "1,000", size: "30", class: "form-control" %>
    <p class="pl-0 align-bottom">円</p>
  <p>販売ステータス</p>
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>

  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>

  <%= f.submit 'Update' %>
  <%= link_to "Back", admin_items_path %>

<% end %>

app/views/admin/items/index.html.erb
<%= link_to '商品を確認する', admin_items_path, class: "btn btn-secondary" %>
<%= link_to 'ユーザーを確認する', admin_customers_path, class: "btn btn-secondary" %>
<%= flash[:notice1] %>

  <h1 class ="mt-5">登録商品</h1>
    <table class="table table-hover">
        <tr>
         <th style="width: 10%"></th>
         <th style="width: 20%">タイトル</th>
         <th>詳細</th>
         <th>値段</th>
         <th>販売ステータス</th>
        </tr>
        <% @items.each do |item| %>
          <tr>
          <td>
          <% if item.image.attached? %>
            <%= image_tag item.image, size: "70x70" %>
          <% else %>
            <%= image_tag 'no_image', size: "70x70" %>
          <% end %>
          </td>
          <td>
          <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
          <% end %>
          </td>
          <td><%= item.introduction %></td>
          <td><%= item.price %></td>
          <% if item.is_active %>
            <td class="text-success align-middle text-center">販売中</td>
          <% else %>
            <td class="text-secondary align-middle text-center">販売停止中</td>
          <% end %>
        <% end %>
    </table>

app/views/admin/items/new.html.erb
<h1>Admin::Items#new</h1>
<p>Find me in app/views/admin/items/new.html.erb</p>

 <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
  <p>タイトル</p>
  <%= f.text_field :name %>

  <p>詳細</p>
  <%= f.text_field :introduction %>
  
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  
  <p>価格</p>
  <%= f.text_field :price, placeholder: "1,000", size: "30", class: "form-control" %>
    <p class="pl-0 align-bottom">円</p>
  <p>販売ステータス</p>
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>

  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>

   <div class="my-2">
    <button type="submit" class="btn btn-success">Create Book</button>
   </div>
<% end %>

app/views/admin/items/show.html.erb
<div class="container mt-3">
  <div class="mx-auto col-lg-12">
    <div class="row">
      <div class="col-10 offset-1">
        <h3 class="page-title">商品詳細</h3>
      </div>
    </div>

    <div class="row">
      <div class="col">
       <% if @item.image.attached? %>
            <%= image_tag item.image, size: "400x300" %>
          <% else %>
            <%= image_tag 'no_image', size: "400x300" %>
          <% end %>
      </div>
      <div class="col">
        <table class="table table-borderless">
          <tr>
            <th style="width: 40%">商品名</th>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <th>商品説明</th>
            <td><%= @item.introduction %></td>
          </tr>
            <th>価格</th>
            <td> <%= @item.price.to_s(:delimited) %> 円</td>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <td>
              <% if @item.is_active %>
              <div class="text-success">販売中</div>
              <% else %>
              <div class="text-secondary">販売停止中</div>
              <% end %>
            </td>
          </tr>
        </table>
        <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success" %>
        <%= link_to '削除する', admin_item_path(@item), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
    <div class="row">
      <div class="d-flex justify-content-start mt-3">
        <%= link_to "戻る", admin_items_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

</div>

app/views/admin/orders/show.html.erb
<h1>Admin::Orders#show</h1>
<p>Find me in app/views/admin/orders/show.html.erb</p>