config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]
    post 'orders/confirm'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :customers, only: [:show, :create, :edit, :update]
    resources :customers do
      member do
        patch 'unsubscribe'
      end
    end
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    resources :orders, only: [:update, :show]
    #patch 'orders' => 'orders#update', as: 'orders'
    resources :customers, only: [:index, :show]
    resources :items
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top', as: 'top'
  end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/adress.rb
class Adress < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :customer
 belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  attribute :adress, :string

  enum payment_method: {クレジットカード:0, 銀行振込:1}
  attribute :status, :integer, default: "0"
  enum status: {入金待ち:0, 入金確認:1,  製作中:2, 発送準備中:3, 発送済み:4}
  attribute :shipping_cost, :integer, default: "500"
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    flash[:notice1] = "You have created item successfully."
    redirect_to admin_items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

 def edit
    @item = Item.find(params[:id])
 end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
      admin_items_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
      root_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiketShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/495e87bfa1.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h1>Tiket Shop</h1>

          <% if customer_signed_in? %>
            <div class="col-2 mt-3 ml-1">
              <%= link_to customer_path(current_customer) do %>
              <i class="fa-solid fa-user"></i>
              <p>マイページ</p>
              <% end %>
            </div>
          <% end %>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if customer_signed_in? %>
                <li class="nav-item p-2">
                  <%= link_to destroy_customer_session_path, method: :delete do%>
                    <div class="d-inline"><i class="fa-solid fa-sign-out-alt"></i></div>
                    <p>Log out</p>
                  <% end %>
                </li>
              <% end %>

              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                   <p>管理人Log out</p>
                  <% end %>
                </li>
              <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="content mb-5">
      <div class="container">
        <div class="col-2">
        </div>

        <div class="col-10">
          <%= yield %>
        </div>

        <div class="col-2">
        </div>

      </div>
    </main>


    <footer class="bg-white">
      <div class="container">
        <p class="fw-light text-center">ensoukai kitene</p>
      </div>
    </footer>

  </body>
</html>